name: GitHub-Profile-Summary-Cards
description: Generate profile summary cards and commit to default branch
author: vn7n24fzkq

inputs:
  USERNAME:
    required: true
    description: 'GitHub username'
    default: ${{ github.repository_owner }}
  BRANCH_NAME:
    required: false
    description: 'The branch to push cards'
    default: 'main'
  UTC_OFFSET:
    required: false
    description: 'The UTC offset used in the Productive Time Card.(e.g., 8, -3)'
    default: 9
  EXCLUDE:
    required: false
    description: 'A comma seperated list of languages to hide'
    default: ''

runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'activity'
  color: 'orange'
